const router=require('express').Router();
const {supabase}=require('../db/supabase');
const {getFiscalSettings}=require('../services/fiscal');
const money=v=>Number((Number(v)||0).toFixed(2));
const profitMargin=(profit,sales)=>Number(sales)>0&&profit!=null?Number(((Number(profit)/Number(sales))*100).toFixed(2)):null;
const startOfDay=v=>v?`${String(v).slice(0,10)}T00:00:00-03:00`:null;
const endOfDay=v=>v?`${String(v).slice(0,10)}T23:59:59.999-03:00`:null;
const chunks=(arr,size=180)=>{const out=[];for(let i=0;i<arr.length;i+=size)out.push(arr.slice(i,i+size));return out};
async function ordersInPeriod(dateFrom,dateTo,maxRows=5000){const from=startOfDay(dateFrom),to=endOfDay(dateTo),out=[],page=800;for(let offset=0;offset<maxRows;offset+=page){let q=supabase.from('marketplace_orders').select('*').eq('marketplace','mercadolivre').order('date_created',{ascending:false}).range(offset,Math.min(offset+page-1,maxRows-1));if(from)q=q.gte('date_created',from);if(to)q=q.lte('date_created',to);const r=await q;if(r.error)throw r.error;out.push(...(r.data||[]));if((r.data||[]).length<page)break}return out}
async function docsFor(ids){const out=[];for(const part of chunks(ids)){if(!part.length)continue;const r=await supabase.from('fiscal_documents').select('*').in('marketplace_order_id',part);if(r.error)throw r.error;out.push(...(r.data||[]))}return out}
async function financialsFor(ids){const out=[];for(const part of chunks(ids)){if(!part.length)continue;const r=await supabase.from('marketplace_sale_financials').select('marketplace_order_id,total_profit,metadata,stock_status').in('marketplace_order_id',part);if(r.error)throw r.error;out.push(...(r.data||[]))}return out}
function summarizeOrder(order,doc,settings){const raw=order.raw_data||{},items=Array.isArray(raw.order_items)?raw.order_items:[],payments=Array.isArray(raw.payments)?raw.payments:[],gross=Number(order.paid_amount??order.total_amount??0),commission=items.reduce((s,i)=>s+Math.abs(Number(i?.sale_fee||0)),0)||payments.reduce((s,p)=>s+Math.abs(Number(p?.marketplace_fee||0)),0),buyer=raw.buyer||{},buyerName=[buyer.first_name,buyer.last_name].filter(Boolean).join(' ').trim()||buyer.nickname||order.buyer_nickname||'Cliente Mercado Livre',productTitle=items.length?items.map(i=>i?.item?.title||'Produto').join(' + '):'Produto Mercado Livre',quantity=items.reduce((s,i)=>s+Number(i?.quantity||0),0);let suggested=Number(settings?.default_discount_percent||0);if(settings?.suggest_ml_commission_as_discount&&gross>0&&commission>0)suggested=Number(((commission/gross)*100).toFixed(4));return{marketplace_order_id:String(order.marketplace_order_id),date_created:order.date_created,marketplace_status:order.status||raw.status||null,buyer_name:String(buyerName),product_title:productTitle,quantity,gross_amount:money(gross),commission_amount:money(commission),suggested_discount_type:'percent',suggested_discount_value:suggested,fiscal:doc||null}}
router.get('/fiscal/queue-period',async(req,res)=>{try{if(!req.query.date_from&&!req.query.date_to)return res.status(400).json({sucesso:false,mensagem:'Informe a data inicial ou final.'});const orders=await ordersInPeriod(req.query.date_from,req.query.date_to),ids=orders.map(o=>String(o.marketplace_order_id)),docs=await docsFor(ids),byOrder=new Map(docs.map(d=>[String(d.marketplace_order_id),d])),settings=await getFiscalSettings(),queue=orders.map(o=>summarizeOrder(o,byOrder.get(String(o.marketplace_order_id))||null,settings));res.json({sucesso:true,total:queue.length,pedidos:queue})}catch(e){res.status(500).json({sucesso:false,mensagem:e.message})}});
router.get('/fiscal/period-summary',async(req,res)=>{try{const orders=await ordersInPeriod(req.query.date_from,req.query.date_to),active=orders.filter(o=>!['cancelled','canceled'].includes(String(o.status||o.raw_data?.status||'').toLowerCase())),ids=active.map(o=>String(o.marketplace_order_id)),fin=await financialsFor(ids),fm=new Map(fin.filter(f=>!f?.metadata?.hidden&&!f?.metadata?.voided).map(f=>[String(f.marketplace_order_id),f])),totalSales=active.reduce((s,o)=>s+Number(o.paid_amount??o.total_amount??0),0);let totalProfit=0,known=0,knownSales=0;for(const o of active){const f=fm.get(String(o.marketplace_order_id));if(f&&f.total_profit!=null){totalProfit+=Number(f.total_profit||0);knownSales+=Number(o.paid_amount??o.total_amount??0);known++}}res.json({sucesso:true,total:active.length,total_vendas:money(totalSales),total_lucro:money(totalProfit),margem_lucro_percent:profitMargin(totalProfit,knownSales),lucros_conhecidos:known,vendas_base_margem:money(knownSales)})}catch(e){res.status(500).json({sucesso:false,mensagem:e.message})}});
module.exports=router;
