-- =========================================================
-- MATRIX AI COMMERCE - MIGRACAO SIC / ERP LEGADO V1
-- Preserva historico sem alterar estoque; apenas saldo-base SIC gera movimento.
-- =========================================================

create table if not exists public.erp_sic_import_runs (
  id bigint generated by default as identity primary key,
  source_name text not null default 'SICNET',
  source_file text,
  backup_sha256 text unique,
  backup_size_bytes bigint,
  backup_observed_at timestamptz,
  status text not null default 'running' check (status in ('running','success','failed')),
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.erp_sic_customers_stage (
  sic_control bigint primary key,
  sic_code text,
  name text,
  document_number text,
  document_type text,
  address_line text,
  address_number text,
  address_complement text,
  neighborhood text,
  city text,
  state text,
  zip_code text,
  phone text,
  mobile text,
  email text,
  contact_name text,
  state_registration text,
  identity_number text,
  profession text,
  birth_date date,
  registered_at date,
  credit_limit numeric(14,2),
  blocked boolean,
  source_raw jsonb not null default '{}'::jsonb,
  imported_at timestamptz not null default now()
);

create table if not exists public.erp_sic_customer_map (
  sic_control bigint primary key references public.erp_sic_customers_stage(sic_control) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  match_method text not null default 'sic_created',
  created_at timestamptz not null default now(),
  unique(customer_id, sic_control)
);

create table if not exists public.erp_sic_product_map (
  sic_control bigint primary key,
  product_id bigint not null references public.inventory_products(id) on delete cascade,
  sic_code text not null,
  created_at timestamptz not null default now(),
  unique(product_id),
  unique(sic_code)
);

create table if not exists public.erp_suppliers (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint unique,
  legacy_code text,
  name text not null,
  contact_name text,
  document_number text,
  state_registration text,
  address_line text,
  neighborhood text,
  city text,
  state text,
  zip_code text,
  phone text,
  fax text,
  email text,
  notes text,
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_sale_types (
  legacy_control bigint primary key,
  name text not null,
  fixed boolean,
  source text not null default 'sic'
);

create table if not exists public.erp_payment_methods (
  legacy_control bigint primary key,
  name text not null,
  fixed boolean,
  source text not null default 'sic'
);

create table if not exists public.erp_sales_channels (
  legacy_control bigint primary key,
  name text not null,
  commission_percent numeric(10,4) not null default 0,
  registered_at date,
  source text not null default 'sic',
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.erp_sales (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  sale_date date,
  sale_time_seconds numeric(12,4),
  sale_type_legacy_control bigint references public.erp_sale_types(legacy_control),
  payment_method_legacy_control bigint references public.erp_payment_methods(legacy_control),
  sales_channel_legacy_control bigint references public.erp_sales_channels(legacy_control),
  sic_customer_control bigint,
  customer_id uuid references public.customers(id) on delete set null,
  is_sale boolean,
  cancelled boolean,
  note_number bigint,
  order_number bigint,
  nfe_number bigint,
  freight_amount numeric(14,2) not null default 0,
  gross_amount numeric(14,2) not null default 0,
  net_amount numeric(14,2) not null default 0,
  estimated_cost_amount numeric(14,2) not null default 0,
  profit_amount numeric(14,2) not null default 0,
  units numeric(14,4) not null default 0,
  item_lines integer not null default 0,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_erp_sales_date on public.erp_sales(sale_date desc);
create index if not exists idx_erp_sales_customer on public.erp_sales(customer_id, sale_date desc);
create index if not exists idx_erp_sales_channel on public.erp_sales(sales_channel_legacy_control, sale_date desc);

create table if not exists public.erp_sale_items (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  sale_legacy_control bigint not null references public.erp_sales(legacy_control) on delete cascade,
  sic_product_control bigint,
  product_id bigint references public.inventory_products(id) on delete set null,
  quantity numeric(14,4) not null default 0,
  gross_total numeric(14,2) not null default 0,
  net_total numeric(14,2) not null default 0,
  profit_amount numeric(14,2) not null default 0,
  surcharge_amount numeric(14,2) not null default 0,
  cancelled_quantity numeric(14,4) not null default 0,
  cancelled_amount numeric(14,2) not null default 0,
  icms_percent numeric(10,4),
  commission_percent numeric(10,4),
  cfop text,
  forecast_date date,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_erp_sale_items_sale on public.erp_sale_items(sale_legacy_control);
create index if not exists idx_erp_sale_items_product on public.erp_sale_items(product_id);

create table if not exists public.erp_sale_payments (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  sale_legacy_control bigint not null references public.erp_sales(legacy_control) on delete cascade,
  payment_method_legacy_control bigint references public.erp_payment_methods(legacy_control),
  amount numeric(14,2) not null default 0,
  change_amount numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_erp_sale_payments_sale on public.erp_sale_payments(sale_legacy_control);

create table if not exists public.erp_purchase_entries (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  entry_date date,
  note_number bigint,
  supplier_legacy_control bigint,
  supplier_id bigint references public.erp_suppliers(id) on delete set null,
  sic_customer_control bigint,
  entry_type text,
  freight_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  units numeric(14,4) not null default 0,
  item_lines integer not null default 0,
  cfop text,
  nfe_access_key text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_erp_purchase_date on public.erp_purchase_entries(entry_date desc);
create index if not exists idx_erp_purchase_supplier on public.erp_purchase_entries(supplier_id, entry_date desc);

create table if not exists public.erp_purchase_items (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  purchase_legacy_control bigint not null references public.erp_purchase_entries(legacy_control) on delete cascade,
  sic_product_control bigint,
  product_id bigint references public.inventory_products(id) on delete set null,
  quantity numeric(14,4) not null default 0,
  total_amount numeric(14,2) not null default 0,
  unit_cost numeric(14,4) not null default 0,
  icms_percent numeric(10,4),
  ipi_amount numeric(14,2),
  included_at date,
  expiry_date date,
  quantity_consumed numeric(14,4),
  cfop text,
  ipi_percent numeric(10,4),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_erp_purchase_items_purchase on public.erp_purchase_items(purchase_legacy_control);
create index if not exists idx_erp_purchase_items_product on public.erp_purchase_items(product_id);

create table if not exists public.erp_quotes (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  quote_date date,
  quote_time_seconds numeric(12,4),
  sic_customer_control bigint,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text,
  contact_name text,
  total_amount numeric(14,2) not null default 0,
  sales_channel_legacy_control bigint references public.erp_sales_channels(legacy_control),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.erp_quote_items (
  id bigint generated by default as identity primary key,
  source text not null default 'sic',
  legacy_control bigint not null unique,
  quote_legacy_control bigint not null references public.erp_quotes(legacy_control) on delete cascade,
  sic_product_control bigint,
  product_id bigint references public.inventory_products(id) on delete set null,
  product_name text,
  quantity numeric(14,4) not null default 0,
  unit_price numeric(14,4) not null default 0,
  real_unit_price numeric(14,4),
  original_unit_price numeric(14,4),
  total_amount numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.erp_audit_logs (
  id bigint generated by default as identity primary key,
  source_table text not null,
  legacy_control bigint,
  event_date date,
  start_time_seconds numeric(12,4),
  end_time_seconds numeric(12,4),
  sic_user_control bigint,
  user_name text,
  level integer,
  station text,
  action text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(source_table, legacy_control)
);

create table if not exists public.erp_legacy_settings (
  section text not null,
  setting_key text not null,
  setting_value text,
  source text not null default 'sic',
  primary key(section, setting_key)
);

create table if not exists public.erp_legacy_reference_data (
  source_table text not null,
  legacy_key text not null,
  display_name text,
  data jsonb not null default '{}'::jsonb,
  primary key(source_table, legacy_key)
);

alter table public.erp_sic_import_runs enable row level security;
alter table public.erp_sic_customers_stage enable row level security;
alter table public.erp_sic_customer_map enable row level security;
alter table public.erp_sic_product_map enable row level security;
alter table public.erp_suppliers enable row level security;
alter table public.erp_sale_types enable row level security;
alter table public.erp_payment_methods enable row level security;
alter table public.erp_sales_channels enable row level security;
alter table public.erp_sales enable row level security;
alter table public.erp_sale_items enable row level security;
alter table public.erp_sale_payments enable row level security;
alter table public.erp_purchase_entries enable row level security;
alter table public.erp_purchase_items enable row level security;
alter table public.erp_quotes enable row level security;
alter table public.erp_quote_items enable row level security;
alter table public.erp_audit_logs enable row level security;
alter table public.erp_legacy_settings enable row level security;
alter table public.erp_legacy_reference_data enable row level security;

grant select, insert, update, delete on table
  public.erp_sic_import_runs,
  public.erp_sic_customers_stage,
  public.erp_sic_customer_map,
  public.erp_sic_product_map,
  public.erp_suppliers,
  public.erp_sale_types,
  public.erp_payment_methods,
  public.erp_sales_channels,
  public.erp_sales,
  public.erp_sale_items,
  public.erp_sale_payments,
  public.erp_purchase_entries,
  public.erp_purchase_items,
  public.erp_quotes,
  public.erp_quote_items,
  public.erp_audit_logs,
  public.erp_legacy_settings,
  public.erp_legacy_reference_data
  to service_role;

grant usage, select on all sequences in schema public to service_role;

create or replace view public.erp_sales_summary
with (security_invoker = true) as
select
  s.*,
  coalesce(c.name, sc.name) as customer_name,
  ch.name as sales_channel_name,
  st.name as sale_type_name,
  pm.name as payment_method_name
from public.erp_sales s
left join public.customers c on c.id = s.customer_id
left join public.erp_sic_customers_stage sc on sc.sic_control = s.sic_customer_control
left join public.erp_sales_channels ch on ch.legacy_control = s.sales_channel_legacy_control
left join public.erp_sale_types st on st.legacy_control = s.sale_type_legacy_control
left join public.erp_payment_methods pm on pm.legacy_control = s.payment_method_legacy_control;

grant select on public.erp_sales_summary to service_role;

create or replace view public.erp_dashboard_summary
with (security_invoker = true) as
select
  (select count(*) from public.erp_sic_customer_map)::bigint as sic_customers,
  (select count(*) from public.erp_sic_product_map)::bigint as sic_products,
  (select count(*) from public.erp_suppliers)::bigint as suppliers,
  (select count(*) from public.erp_sales)::bigint as sales,
  (select count(*) from public.erp_sale_items)::bigint as sale_items,
  (select count(*) from public.erp_purchase_entries)::bigint as purchases,
  (select count(*) from public.erp_purchase_items)::bigint as purchase_items,
  (select count(*) from public.erp_quotes)::bigint as quotes,
  (select coalesce(sum(on_hand),0) from public.inventory_stock p where exists (select 1 from public.erp_sic_product_map m where m.product_id=p.product_id))::numeric(14,4) as sic_stock_units,
  (select coalesce(sum(stock_value),0) from public.inventory_stock p where exists (select 1 from public.erp_sic_product_map m where m.product_id=p.product_id))::numeric(14,2) as sic_stock_value;

grant select on public.erp_dashboard_summary to service_role;
