create table if not exists public.manual_sales (
  id uuid primary key default gen_random_uuid(),
  sale_number bigint generated by default as identity,
  sale_date timestamptz not null default now(),
  origin text not null default 'manual',
  customer_name text,
  customer_document text,
  customer_phone text,
  customer_email text,
  customer_address jsonb not null default '{}'::jsonb,
  gross_amount numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  net_sale_amount numeric(14,2) not null default 0,
  payment_method text,
  notes text,
  status text not null default 'active',
  stock_status text not null default 'pending',
  total_cost numeric(14,2),
  total_profit numeric(14,2),
  margin_percent numeric(8,2),
  nfe_status text,
  nfe_amount numeric(14,2),
  nfe_number text,
  nfe_access_key text,
  bling_nfe_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists manual_sales_sale_number_uq on public.manual_sales(sale_number);
create index if not exists manual_sales_sale_date_idx on public.manual_sales(sale_date desc);
create table if not exists public.manual_sale_items (
  id bigint generated by default as identity primary key,
  sale_id uuid not null references public.manual_sales(id) on delete cascade,
  product_id bigint not null references public.inventory_products(id),
  product_sku text, product_name text, product_type text,
  quantity numeric(14,4) not null check(quantity>0),
  unit_price numeric(14,2) not null default 0,
  line_total numeric(14,2) not null default 0,
  unit_cost numeric(14,4), cost_total numeric(14,2),
  stock_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists manual_sale_items_sale_idx on public.manual_sale_items(sale_id);
create table if not exists public.manual_sale_audit (
  id bigint generated by default as identity primary key,
  sale_id uuid not null references public.manual_sales(id) on delete cascade,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists manual_sale_audit_sale_idx on public.manual_sale_audit(sale_id,created_at desc);
alter table public.manual_sales enable row level security;
alter table public.manual_sale_items enable row level security;
alter table public.manual_sale_audit enable row level security;
grant all on public.manual_sales,public.manual_sale_items,public.manual_sale_audit to service_role;
grant usage,select on all sequences in schema public to service_role;