-- =========================================================
-- MATRIX AI COMMERCE - STOCK MATRIX + CLIENTES + FISCAL + BLING V1
-- Execute UMA vez no Supabase SQL Editor.
-- Não remove tabelas existentes.
-- =========================================================

create table if not exists public.inventory_products (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  description text,
  category text,
  product_type text not null default 'component' check (product_type in ('component','simple','kit','service')),
  unit text not null default 'UN',
  minimum_stock numeric(14,4) not null default 0,
  average_cost numeric(14,4) not null default 0,
  supplier_name text,
  location_code text,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_marketplace_links (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.inventory_products(id) on delete cascade,
  marketplace text not null,
  account_id text,
  external_item_id text not null,
  external_user_product_id text,
  variation_id text,
  seller_sku text,
  sync_enabled boolean not null default true,
  last_external_quantity numeric(14,4),
  last_sync_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_inventory_marketplace_link
on public.inventory_marketplace_links (
  marketplace,
  external_item_id,
  coalesce(variation_id, '')
);

create table if not exists public.inventory_bom_components (
  id bigint generated by default as identity primary key,
  parent_product_id bigint not null references public.inventory_products(id) on delete cascade,
  component_product_id bigint not null references public.inventory_products(id) on delete restrict,
  quantity numeric(14,4) not null check (quantity > 0),
  notes text,
  created_at timestamptz not null default now(),
  unique(parent_product_id, component_product_id)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.inventory_products(id) on delete restrict,
  quantity numeric(14,4) not null,
  movement_type text not null,
  unit_cost numeric(14,4),
  reference_type text,
  reference_id text,
  marketplace_order_id text,
  idempotency_key text unique,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_movements_product on public.inventory_movements(product_id, created_at desc);
create index if not exists idx_inventory_movements_order on public.inventory_movements(marketplace_order_id);

create table if not exists public.inventory_reservations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.inventory_products(id) on delete cascade,
  quantity numeric(14,4) not null check (quantity > 0),
  reference_type text,
  reference_id text,
  status text not null default 'active' check (status in ('active','released','consumed')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace view public.inventory_stock as
select
  p.id as product_id,
  p.sku,
  p.name,
  p.category,
  p.product_type,
  p.unit,
  p.minimum_stock,
  p.average_cost,
  p.supplier_name,
  p.location_code,
  p.active,
  coalesce(m.on_hand, 0)::numeric(14,4) as on_hand,
  coalesce(r.reserved, 0)::numeric(14,4) as reserved,
  (coalesce(m.on_hand, 0) - coalesce(r.reserved, 0))::numeric(14,4) as available,
  ((coalesce(m.on_hand, 0) - coalesce(r.reserved, 0)) <= p.minimum_stock) as below_minimum,
  (coalesce(m.on_hand, 0) * p.average_cost)::numeric(14,2) as stock_value
from public.inventory_products p
left join (
  select product_id, sum(quantity) as on_hand
  from public.inventory_movements
  group by product_id
) m on m.product_id = p.id
left join (
  select product_id, sum(quantity) as reserved
  from public.inventory_reservations
  where status = 'active'
  group by product_id
) r on r.product_id = p.id;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  source text,
  marketplace_buyer_id text,
  marketplace_nickname text,
  name text not null,
  email text,
  phone text,
  document_type text,
  document_number text,
  address_line text,
  address_number text,
  neighborhood text,
  city text,
  state text,
  zip_code text,
  country text default 'BR',
  bling_contact_id text,
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_customers_document
on public.customers(document_number)
where document_number is not null;

create index if not exists idx_customers_marketplace_buyer
on public.customers(marketplace_buyer_id);

create table if not exists public.fiscal_settings (
  id integer primary key default 1 check (id = 1),
  default_discount_percent numeric(9,4) not null default 0,
  suggest_ml_commission_as_discount boolean not null default true,
  require_manual_confirmation boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.fiscal_settings(id)
values (1)
on conflict (id) do nothing;

create table if not exists public.fiscal_documents (
  id bigint generated by default as identity primary key,
  marketplace_order_id text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  gross_amount numeric(14,2) not null default 0,
  commission_amount numeric(14,2) not null default 0,
  freight_amount numeric(14,2) not null default 0,
  operational_net_amount numeric(14,2) not null default 0,
  discount_percent numeric(9,4) not null default 0,
  fiscal_amount numeric(14,2) not null default 0,
  bling_contact_id text,
  bling_order_id text,
  bling_nfe_id text,
  nfe_number text,
  nfe_series text,
  nfe_access_key text,
  nfe_pdf_url text,
  status text not null default 'preview',
  bling_request jsonb,
  bling_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bling_accounts (
  id bigint generated by default as identity primary key,
  access_token text not null,
  refresh_token text,
  token_type text,
  scope text,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- RLS e permissões server-side
alter table public.inventory_products enable row level security;
alter table public.inventory_marketplace_links enable row level security;
alter table public.inventory_bom_components enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.inventory_reservations enable row level security;
alter table public.customers enable row level security;
alter table public.fiscal_settings enable row level security;
alter table public.fiscal_documents enable row level security;
alter table public.bling_accounts enable row level security;

grant select, insert, update, delete on table public.inventory_products to service_role;
grant select, insert, update, delete on table public.inventory_marketplace_links to service_role;
grant select, insert, update, delete on table public.inventory_bom_components to service_role;
grant select, insert, update, delete on table public.inventory_movements to service_role;
grant select, insert, update, delete on table public.inventory_reservations to service_role;
grant select on table public.inventory_stock to service_role;
grant select, insert, update, delete on table public.customers to service_role;
grant select, insert, update, delete on table public.fiscal_settings to service_role;
grant select, insert, update, delete on table public.fiscal_documents to service_role;
grant select, insert, update, delete on table public.bling_accounts to service_role;
grant usage, select on all sequences in schema public to service_role;
