-- =========================================================
-- MATRIX AI COMMERCE - FINANCEIRO & PATRIMONIO V1
-- Execute UMA vez no Supabase SQL Editor.
-- Nao remove tabelas existentes.
-- =========================================================

create table if not exists public.financial_accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  account_type text not null check (account_type in ('asset','liability')),
  category text not null,
  source text not null default 'manual',
  current_balance numeric(16,2) not null default 0,
  include_in_total boolean not null default true,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_financial_accounts_type on public.financial_accounts(account_type, active);
create index if not exists idx_financial_accounts_source on public.financial_accounts(source, active);

create table if not exists public.financial_entries (
  id bigint generated by default as identity primary key,
  account_id bigint references public.financial_accounts(id) on delete set null,
  entry_type text not null check (entry_type in ('income','expense','adjustment')),
  amount numeric(16,2) not null,
  description text not null,
  source text not null default 'manual',
  reference_type text,
  reference_id text,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_financial_entries_date on public.financial_entries(occurred_at desc);
create index if not exists idx_financial_entries_account on public.financial_entries(account_id, occurred_at desc);

create table if not exists public.financial_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  asset_total numeric(16,2) not null default 0,
  liability_total numeric(16,2) not null default 0,
  net_worth numeric(16,2) not null default 0,
  cash_total numeric(16,2) not null default 0,
  stock_total numeric(16,2) not null default 0,
  marketplace_receivable numeric(16,2) not null default 0,
  accounts_receivable numeric(16,2) not null default 0,
  accounts_payable numeric(16,2) not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.financial_connections (
  id bigint generated by default as identity primary key,
  provider text not null,
  institution_name text,
  connection_type text not null default 'open_finance',
  status text not null default 'pending',
  external_connection_id text,
  read_only boolean not null default true,
  last_sync_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.financial_accounts enable row level security;
alter table public.financial_entries enable row level security;
alter table public.financial_snapshots enable row level security;
alter table public.financial_connections enable row level security;

grant select, insert, update, delete on table public.financial_accounts to service_role;
grant select, insert, update, delete on table public.financial_entries to service_role;
grant select, insert, update, delete on table public.financial_snapshots to service_role;
grant select, insert, update, delete on table public.financial_connections to service_role;
grant usage, select on all sequences in schema public to service_role;
