-- =========================================================
-- MATRIX AI COMMERCE - SUBSTITUTOS DE COMPONENTES DOS KITS
-- Preparado para revisão. Não executar em produção antes da aprovação.
-- =========================================================

create table if not exists public.inventory_bom_substitutes (
  id bigint generated by default as identity primary key,
  bom_component_id bigint not null
    references public.inventory_bom_components(id) on delete cascade,
  substitute_product_id bigint not null
    references public.inventory_products(id) on delete restrict,
  priority integer not null default 1 check (priority > 0),
  quantity_factor numeric(14,4) not null default 1 check (quantity_factor > 0),
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bom_component_id, substitute_product_id)
);

create index if not exists idx_inventory_bom_substitutes_component
  on public.inventory_bom_substitutes(bom_component_id, priority, id);

create index if not exists idx_inventory_bom_substitutes_product
  on public.inventory_bom_substitutes(substitute_product_id);

alter table public.inventory_bom_substitutes enable row level security;

grant select, insert, update, delete
  on table public.inventory_bom_substitutes to service_role;

grant usage, select on all sequences in schema public to service_role;
